config/routes.rb
ShopManager::Application.routes.draw do
  resources :orders
  resources :users
  resources :orderdetails
  resources :carts
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :products
  
  root to: "main_pages#home"
  match '/signup', to: 'users#new'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/edit', to: 'users#edit'
  match '/new_product', to: 'products#new'

  match '/new_category', to: "categories#new"
  match '/new_cart', to:"carts#new"
  match '/new_order', to: "orders#new"
  match '/cancel', to: "orders#cancel"

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  before_save :create_remember_token
  has_many :products, dependent: :destroy
  validates :name, presence: true, uniqueness: { case_sensitive: false }

   private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_filter :sign_in_user , only:[:edit,:create,:destroy,:update]
	def show
		@category=Category.find(params[:id])
		@products=@category.products.paginate(page: params[:page])
		cookies.permanent[:remember_token_category] = @category.remember_token
	end

	

	def  new
		@category=Category.new		
	end

	def create
		@category=Category.create(params[:category])
		if @category.save
			flash[:success]="New Category Added"
			redirect_to categories_path
		else
			render 'new'	
		end
	end

	def edit
	@category=Category.find(params[:id])
	cookies.permanent[:remember_token_category] = @category.remember_token


	 #@current_category=@category
	# create_current_category=(@category)

	end

	def update
		@category=Category.find(params[:id])
		if @category.update_attributes(params[:category])
			flash[:success] = "category Updated!"
			redirect_to categories_path
		else
			render 'edit'
		end
		
		
	end

	def  destroy
		category=Category.find(params[:id]).destroy
		flash[:success]="Deleted Category #{category.name}"
		redirect_to categories_path
		
	end

	def index
		@categories=Category.paginate(page: params[:page])
	end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h1> New Category </h1>
<div class=" hero-unit">

	<div>
			<%= form_for(@category) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			<%= f.submit "Save Change?", class: "btn btn-large btn-primary" %>
			

			<% end %>
			<%= link_to "Add Product",new_product_path, class: "btn btn-large btn-primary"%>
</div>

</div>

app/views/categories/index.html.erb
<h1> Categories Page</h1>
<div class="row">
	<div class="offset3">
		<aside>
			
			<%= link_to "New Category", new_category_path, class: "btn btn-large btn-primary" unless !signed_in? ||!current_user.admin%>
			<%= will_paginate @categories %>
			<ul class="categories">
		
		<% @categories.each do |cat| %>
		<li><h3><%= cat.name %></h3>
		
			<%= link_to "View Products", cat %>
		<% if signed_in? && current_user.admin %>
			|<%= link_to "Edit",edit_category_path(cat)%>
			|<a href="<%= new_product_path %>?id=<%= cat.id %>"> Add Product </a>
			|<%= link_to "Add Product",new_product_path, id: cat.id %>
			|<%= link_to "Delete", cat, method: "delete", data: {confirm: "You Sure?"} %>
			<% end %>
		</li>
		<% end %>
	</ul>
	</br>
		
	</aside>
	</div>

</div>

app/views/categories/new.html.erb
<h1> New Category </h1>
<div class=" hero-unit">
	<aside>
		<div>
			<%= form_for(@category) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			<%= f.submit "Add", class: "btn btn-large btn-primary" %>
			<% end %>
		</div>
</aside>
</div>

app/views/categories/show.html.erb
<div class="span8 offset3">

<h1><%= @category.name %> (<%= @products.count %>)  </h1>
<%= will_paginate @products %>
	<ul style="list-style:none;">

	<% @products.each do |p| %>
	<section>
<li style="border-bottom:solid 1px green;">	
		
		<%= gravatar_for_product(p, size: 40) %>
		<h3> <%= p.name %>
		<h4> Price: <%= p.cost %> </h4>
		</h3>
			<%= link_to "View detail", p %>
		<% if signed_in? %>
			|<%= link_to "Edit", edit_product_path(p) %>
			|<%= link_to "Delete", p, method: "delete", data: {confirm: "You Sure?"} %>
		<%end %>
</li>
</section>
	<% end %>

</ul>
<%= will_paginate @products %>
</div>
<% if  !current_user.nil? &&current_user.admin  %>
<div class="center "> 
	<%= link_to "Add new Product", new_product_path, class: "btn btn-small btn-primary" %>
	<div>
<% end %>