config/routes.rb
ShopManager::Application.routes.draw do
  resources :orders
  resources :users
  resources :orderdetails
  resources :carts
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :products
  
  root to: "main_pages#home"
  match '/signup', to: 'users#new'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/edit', to: 'users#edit'
  match '/new_product', to: 'products#new'

  match '/new_category', to: "categories#new"
  match '/new_cart', to:"carts#new"
  match '/new_order', to: "orders#new"
  match '/cancel', to: "orders#cancel"

  

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :cost, :name,:image_url,:description

  before_save :create_img
  belongs_to :categroy
  belongs_to :cart
 
  validates :name, presence: true,  uniqueness: { case_sensitive: false }
  validates :cost, presence: true


def create_img
	self.description="Mo ta san pham #{self.name}@railstutorial.org Mo ta san pham #{self.name}@railstutorial.orgMo ta san pham #{self.name}@railstutorial.orgMo ta san pham #{self.name}@railstutorial.orgMo ta san pham #{self.name}@railstutorial.orgMo ta san pham #{self.name}@railstutorial.orgMo ta san pham #{self.name}@railstutorial.orgMo ta san pham #{self.name}@railstutorial.orgMo ta san pham #{self.name}@railstutorial.org"
	
end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_filter :sign_in_user, only:[:new,:create,:destroy,:edit,:update]
	def new
		if cookies[:remember_token_category].nil?
		 category=(Category.find(params[:id]))
		 cookies.permanent[:remember_token_category] = category.remember_token
		end
		@product=Product.new
		
	end

	def create

		
		@product=current_category.products.build(params[:product])
		if @product.save
			flash[:sucess]="New Product Added to #{current_category.name}"
			redirect_to categories_url
		else
			render 'new'
		end	
		
	end
	def show
			@product=Product.find(params[:id])			
			cookies.permanent[:remember_product] = @product.id
	end

	def  edit
		@product=Product.find(params[:id])
	end


	def update
		@product=Product.find(params[:id])
		if @product.update_attributes(params[:product])
			flash[:sucess]="Product updated"
			redirect_to current_category
		else
			render 'edit'
		end
	end

	def  destroy
	Product.find(params[:id]).destroy
	flash[:sucess]="Deleted product"
	redirect_to current_category

		
	end
end

app/helpers/products_helper.rb
module ProductsHelper
	def gravatar_for_product(product, options = { size: 50 })
		if !product.image_url.nil?
    gravatar_id = Digest::MD5::hexdigest(product.image_url)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: product.name, class: "gravatar")
  end
  end
end

app/views/products/edit.html.erb
<h1> Edit Product </h1>
<div class="row">
<%= form_for(@product) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :cost, "Price" %>
	<%= f.text_field :cost %>
	<%= f.label :image_url, "Url Image" %>
	<%= f.text_field :image_url  %>
	<%= f.submit "Save Change Product?", class:"btn btn-large btn-primary" %>
	</div>
	<% end %>

app/views/products/new.html.erb
<h1> <%= current_category.name  %>  </h1>

<div class="row">

	<div class="span4 offset3">
		<%= form_for(@product) do |f| %>
		<%= render 'shared/error_messages',object: f.object %>
		<%= f.label :name %>
		<%= f.text_field :name %>
		<%= f.label :cost, "Price" %>
		<%= f.text_field :cost %>
		<%= f.label :image_url %>
		<%= f.text_field :image_url %>
		<%= f.submit "Add New Product" , class:"btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/products/show.html.erb
<h1> View Product </h1>
<div class="span6 offset3">
<div class="span4">
	<div id="image">
	<h1><%= gravatar_for_product @product, size:100 %><h1>
	</div>
	<div id="info" style="clear:both;">
	<h4>Name:  <%= @product.name %></h4>
	<h5>Price: <%= @product.cost %></h5>
	
	<b><%= link_to "Add to cart", new_cart_path %></b>
	
	<% if !current_user.nil? && current_user.admin   %> 
	<%= link_to "Edit Product", edit_product_path(@product) %>
	<% end %> 
	
</br>

	<b>Description: </b></br> <p class="des_product"><%= @product.description %></p>
	
</div>
	</div>
</div>