config/routes.rb
ShopManager::Application.routes.draw do
  resources :orders
  resources :users
  resources :orderdetails
  resources :carts
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :products
  
  root to: "main_pages#home"
  match '/signup', to: 'users#new'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/edit', to: 'users#edit'
  match '/new_product', to: 'products#new'

  match '/new_category', to: "categories#new"
  match '/new_cart', to:"carts#new"
  match '/new_order', to: "orders#new"
  match '/cancel', to: "orders#cancel"

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
 <li><%= link_to "About",'#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Shop Manager", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <% if current_user.admin? %>
            <li > <%= link_to "Users", users_path %> </li>
            <li> <%= link_to "Categories", categories_path %>
              <li> <%= link_to "Orders", orders_path %> </li>

            <% end %>
             <li><%= link_to "Cart", carts_path %> </li>
          <li><%= link_to "Logout", logout_path, method: "delete" %></li>
          <% else %>
          <li> <%= link_to "Login", login_path%> </li>

          <% end %>
        
          </ul>

      </nav>

    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">	

<%= render 'layouts/header' %>
 <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
<%= yield %>
 
	<%= render 'layouts/footer' %>
</div>
</body>
</html>